apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'dagger.hilt.android.plugin'

apply from: "$project.rootDir/buildsystem/java_version.gradle"

android {
    namespace "com.vlad1m1r.bltaxi.taxi.ui"
    defaultConfig {

        testOptions.unitTests.includeAndroidResources = true
    }

    buildTypes {
        debug {
            minifyEnabled false
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            minifyEnabled false
            enableUnitTestCoverage false
            enableAndroidTestCoverage false
        }
    }

    buildFeatures {
        buildConfig = true
        compose = true
    }

    testOptions {
        animationsDisabled = true
        unitTests.all {
            systemProperty 'robolectric.dependency.repo.url', 'https://repo1.maven.org/maven2'
        }
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    implementation libs.kotlin.coroutines.android

    implementation libs.hilt.android
    ksp libs.hilt.compiler

    // Compose
    implementation platform(libs.compose.bom)
    implementation libs.compose.material
    implementation libs.compose.ui.tooling.preview
    implementation libs.compose.runtime
    implementation "androidx.compose.material:material-icons-core"
    implementation "androidx.compose.material:material-icons-extended"
    debugImplementation libs.compose.ui.tooling

    // Compose integration
    implementation libs.compose.activity
    implementation libs.compose.lifecycle.viewmodel
    implementation libs.hilt.navigation.compose

    // Lifecycle
    implementation "androidx.lifecycle:lifecycle-runtime-compose:2.8.7"

    implementation project(":taxi:data")
    implementation project(":basedata")
    implementation project(":baseui")
    implementation project(":taxi:domain")
    implementation project(":about:domain")
    implementation project(":analytics")
    implementation project(":shortcuts")

    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation libs.mockito.kotlin
    testImplementation libs.mockito.inline
    testImplementation libs.robolectric
    testImplementation libs.arch.core.testing
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2"
}
