apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'dagger.hilt.android.plugin'

apply from: "$project.rootDir/buildsystem/java_version.gradle"

android {
    namespace "com.vlad1m1r.bltaxi.settings.ui"
    defaultConfig {

        testOptions.unitTests.includeAndroidResources = true
    }

    buildTypes {
        debug {
            minifyEnabled false
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            minifyEnabled false
            enableUnitTestCoverage false
            enableAndroidTestCoverage false
        }
    }

    testOptions {
        animationsDisabled = true
        unitTests.all {
            systemProperty 'robolectric.dependency.repo.url', 'https://repo1.maven.org/maven2'
        }
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    implementation libs.hilt.android
    kapt libs.hilt.compiler

    api libs.preference.ktx

    implementation project(":baseui")
    implementation project(":analytics")
    implementation project(":basedata")

    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation libs.mockito.kotlin
    testImplementation libs.mockito.inline
    testImplementation libs.robolectric
}
