// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:8.13.0"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.20"
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:2.2.20-2.0.3"
        classpath "com.google.gms:google-services:4.4.0"
        classpath "com.google.firebase:firebase-crashlytics-gradle:2.8.1"
        classpath "com.google.dagger:hilt-android-gradle-plugin:2.56"
        classpath 'com.github.ben-manes:gradle-versions-plugin:0.51.0'
    }
}

apply plugin: 'com.github.ben-manes.versions'

allprojects {
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

// Configure Gradle Versions Plugin to reject unstable versions
tasks.named("dependencyUpdates").configure {
    rejectVersionIf {
        def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { keyword -> candidate.version.toUpperCase().contains(keyword) }
        def unstableKeyword = ['ALPHA', 'BETA', 'RC', 'DEV', 'SNAPSHOT'].any { keyword -> candidate.version.toUpperCase().contains(keyword) }
        return !stableKeyword && unstableKeyword
    }

    // Check for updates from release versions only
    checkForGradleUpdate = true
    outputFormatter = "plain,html"
    outputDir = "build/dependencyUpdates"
    reportfileName = "report"
}
