// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath libs.gradle.plugin
        classpath libs.kotlin.gradle.plugin
        classpath libs.kotlin.compose.compiler.plugin
        classpath libs.kotlin.serialization.plugin
        classpath libs.ksp.gradle.plugin
        classpath libs.google.services.plugin
        classpath libs.firebase.crashlytics.plugin
        classpath libs.hilt.gradle.plugin
        classpath libs.gradle.versions.plugin
    }
}

apply plugin: 'com.github.ben-manes.versions'

allprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://jitpack.io' }
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

// Configure Gradle Versions Plugin to reject unstable versions
tasks.named("dependencyUpdates").configure {
    rejectVersionIf {
        def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { keyword -> candidate.version.toUpperCase().contains(keyword) }
        def unstableKeyword = ['ALPHA', 'BETA', 'RC', 'DEV', 'SNAPSHOT'].any { keyword -> candidate.version.toUpperCase().contains(keyword) }
        return !stableKeyword && unstableKeyword
    }

    // Check for updates from release versions only
    checkForGradleUpdate = true
    outputFormatter = "plain,html"
    outputDir = "build/dependencyUpdates"
    reportfileName = "report"
}
