apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'dagger.hilt.android.plugin'

apply from: "$project.rootDir/buildsystem/java_version.gradle"

android {
    namespace "com.vlad1m1r.bltaxi.taxi.data"

    buildTypes {
        debug {
            minifyEnabled false
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            minifyEnabled false
            enableUnitTestCoverage false
            enableAndroidTestCoverage false
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.kotlin.coroutines.android

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    implementation project(Modules.taxi_domain)
    implementation project(Modules.local)
    implementation project(Modules.remote)

    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation libs.mockito.kotlin
}
