apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

apply from: "$project.rootDir/buildsystem/java_version.gradle"

android {
    namespace = "com.vlad1m1r.bltaxi.taxi.domain"

    buildTypes {
        debug {
            minifyEnabled = false
            enableUnitTestCoverage = true
            enableAndroidTestCoverage = true
        }
        release {
            minifyEnabled = false
            enableUnitTestCoverage = false
            enableAndroidTestCoverage = false
        }
    }
}

dependencies {
    implementation libs.kotlin.coroutines.core
    implementation libs.appcompat

    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation libs.mockito.kotlin
    testImplementation libs.mockito.inline
}
