apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'dagger.hilt.android.plugin'

apply from: '../buildsystem/java_version.gradle'

android {
    namespace "com.vlad1m1r.baseui"

    buildTypes {
        debug {
            minifyEnabled false
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            minifyEnabled false
            enableUnitTestCoverage false
            enableAndroidTestCoverage false
        }
    }

    buildFeatures {
        dataBinding = true
        compose = true
    }
}

dependencies {
    implementation libs.kotlin.coroutines.core

    api libs.recyclerview
    api libs.material.design
    api libs.cardview
    api libs.constraint.layout
    api libs.appcompat
    api libs.core.ktx

    // Compose
    implementation platform(libs.compose.bom)
    api libs.compose.material
    api libs.compose.ui.tooling.preview
    api libs.compose.runtime

    implementation libs.hilt.android
    ksp libs.hilt.compiler

    api libs.navigation.fragment
    api libs.navigation.ui

    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation libs.mockito.kotlin
}
