apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.devtools.ksp'
apply plugin: 'dagger.hilt.android.plugin'

apply from: "$project.rootDir/buildsystem/java_version.gradle"

android {
    namespace "com.vlad1m1r.bltaxi.about.ui"

    buildTypes {
        debug {
            minifyEnabled false
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            minifyEnabled false
            enableUnitTestCoverage false
            enableAndroidTestCoverage false
        }
    }

    buildFeatures {
        dataBinding = true
    }

    testOptions {
        animationsDisabled = true
        unitTests.all {
            systemProperty 'robolectric.dependency.repo.url', 'https://repo1.maven.org/maven2'
        }
    }
}

dependencies {
    implementation libs.kotlin.coroutines.android

    implementation libs.hilt.android
    ksp libs.hilt.compiler

    implementation libs.appcompat

    implementation project(":baseui")
    implementation project(":about:domain")
    implementation project(":basedata")

    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation libs.mockito.kotlin
    testImplementation libs.mockito.inline
    testImplementation libs.robolectric

    kspTest libs.databinding.compiler
}
