apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'dagger.hilt.android.plugin'

apply from: '../buildsystem/java_version.gradle'

android {
    namespace "com.vlad1m1r.bltaxi.sync"

    buildTypes {
        debug {
            minifyEnabled false
            enableUnitTestCoverage true
            enableAndroidTestCoverage true
        }
        release {
            minifyEnabled false
            enableUnitTestCoverage false
            enableAndroidTestCoverage false
        }
    }
}

dependencies {
    implementation libs.work.manager

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    api libs.hilt.work
    kapt libs.hilt.android.compiler

    implementation project(Modules.remote)
    implementation project(Modules.local)
    implementation project(Modules.taxi_domain)

    testImplementation libs.junit
    testImplementation libs.truth
    testImplementation libs.mockito.kotlin
    testImplementation libs.robolectric
    testImplementation libs.work.manager.test
}
